export interface VwBuildings {
  id: number;
  buildingNameAr: string;
  buildingNameEn: string;
  ownerId: number | null;
  cityId: number | null;
  areaSize: number | null;
  realestateId: number | null;
  subRealestateId: number | null;
  officeId: number | null;
  unitNumber: number | null;
  galleriesNumber: number | null;
  parkingSlotsNumber: number | null;
  subParkingNumber: number | null;
  elevatorNumber: number | null;
  propertyType: number | null;
  roleNumber: number | null;
  deedNumber: number | null;
  propertyDeedDate: string | null;
  permitNumber: number | null;
  permitDate: string | null;
  buildingAddress: string;
  countryId: number | null;
  regionId: number | null;
  costCenterId: number | null;
  deferredRevenueAccountId: number | null;
  accuredRevenueAccountId: number | null;
  taxAccountId: number | null;
  insuranceAccountId: number | null;
  serviceAccountId: number | null;
  buildingLicenseNumber: string;
  propertyInstrument: string;
  propertyInstrumentDate: string | null;
  issueDate: string | null;
  ownerNameEn: string;
  ownerNameAr: string;
  realestateNameAr: string;
  realestateNameEn: string;
  officeNameEn: string;
  officeNameAr: string;
  countryNameAr: string;
  countryNameEn: string;
  cityNameAr: string;
  cityNameEn: string;
  regionNameAr: string;
  regionNameEn: string;
}
