export class SuppliersVM
{
    id:any;
    supplierNameAr!:string;
    supplierNameEn!:string;
    phone!:string;
    mobile!:string;
    fax!:string;
    email!:string;
    identityNumber!:string;
    identityIssuanceDate!:Date;
    identityIssuancePlace!:string;
    identityExpireDate!:Date;
    nationalityId:any;
    job!:string;
    countryId:any;
    regionId:any;
    cityId:any;
    districtId:any;
    blockNumber!:string;
    apartmentNumber!:string;
    postalCode!:string;
    additionalCode!:string;
    detailedAddress!:string;
    nationalityNameAr!:string;
    nationalityNameEn!:string;
    countryNameAr!:string;
    countryNameEn!:string;
    cityNameAr!:string;
    cityNameEn!:string;
    regionNameAr!:string;
    regionNameEn!:string;
    districtNameAr!:string;
    districtNameEn!:string;
    userId:any;
    supplierAccountId:any;
    expenseAccountId:any;
    taxAccountId:any;
}