export class Suppliers
{
    id:any;
    supplierNameAr!:string;
    supplierNameEn!:string;
    phone!:string;
    mobile!:string;
    fax!:string;
    email!:string;
    identityNumber!:string;
    identityIssuanceDate!:Date;
    identityIssuancePlace!:string;
    identityExpireDate!:Date;
    nationalityId:any;
    job!:string;
    countryId:any;
    regionId:any;
    cityId:any;
    districtId:any;
    blockNumber!:string;
    apartmentNumber!:string;
    postalCode!:string;
    additionalCode!:string;
    detailedAddress!:string;
    supplierAccountId:any;
    expenseAccountId:any;
    taxAccountId:any;
}